---
name: "auto-generate-release-notes"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set release version
        id: release_version
        run: |
          echo ::set-output name=version::$GITHUB_SHA
          echo $GITHUB_SHA
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.release_version.outputs.version }}
          prerelease: false
