---
name: "auto-generate-release-notes"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set release version
        id: release_version
        run: |
          echo ${ GITHUB_SHA }
      - uses: "marvinpinto/action-automatic-releases@latest"
        env: |
          VERSION: 1.0.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 'github.event.push.head.sha'
          prerelease: false
