---
name: "auto-generate-release-notes"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.head.sha }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: '${{ github.event.push.head.sha }}'
          prerelease: false
