---
name: "auto-generate-release-notes"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: "minor"
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        automatic_release_tag: ${{ steps.tag_version.outputs.new_version }}
        title: Release ${{ steps.tag_version.outputs.new_varsion }}
        draft: false
        prerelease: false
